export const INITIAL_AUTH_STATE: AuthState = {
    email: '',
    emailConfirmationSent: false,
	isEmailVerified: false,
	token: ''
};

export enum SEND_EMAIL_CONFIRMATION {
	SEND_EMAIL_CONFIRMATION_START = '@@auth/SEND_EMAIL_CONFIRMATION_START',
	SEND_EMAIL_CONFIRMATION_SUCCESS = '@@auth/SEND_EMAIL_CONFIRMATION_SUCCESS',
	SEND_EMAIL_CONFIRMATION_FAIL = '@@auth/SEND_EMAIL_CONFIRMATION_FAIL'
}

export enum CONFIRM_EMAIL {
	CONFIRM_EMAIL_START = '@@auth/CONFIRM_EMAIL_START',
	CONFIRM_EMAIL_SUCCESS = '@@auth/CONFIRM_EMAIL_SUCCESS',
	CONFIRM_EMAIL_FAIL = '@@auth/CONFIRM_EMAIL_FAIL'
}

export enum REGISTER_USER {
	REGISTER_USER_START = '@@auth/REGISTER_USER_START',
	REGISTER_USER_SUCCESS = '@@auth/REGISTER_USER_SUCCESS',
	REGISTER_USER_FAIL = '@@auth/REGISTER_USER_FAIL'
}

export enum LOGIN_USER {
	LOGIN_USER_START = '@@auth/LOGIN_USER_START',
	LOGIN_USER_SUCCESS = '@@auth/LOGIN_USER_SUCCESS',
	LOGIN_USER_FAIL = '@@auth/LOGIN_USER_FAIL'
}
